name: cw-geodata
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - shapely
  - pandas
  - geopandas
  - numpy
  - scipy
  - scikit-image
  - rtree
  - networkx
  - rasterio
  - pip:
    - affine
    - osmnx
