name: cw-geodata
dependencies:
  - python=3.6
  - pip=18.1  # pinned because 19.0.3 was having issues with certifi install
  - shapely
  - fiona
  - pandas
  - geopandas
  - numpy
  - scikit-image
  - networkx
  - rasterio
  - pip:
    - affine
    - osmnx
