language: python
sudo: true
python:
  - "3.6"

before_install:
# get kcov for testing CLI scripts
- wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz

# command to install dependencies
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # switch python version spec in environment.yml to match TRAVIS_PYTHON_VERSION
  # annoying workaround to `conda env create python=$TRAVIS_PYTHON_VERSION` not working
  - sed -i -E 's/(python=)(.*)/\1'$TRAVIS_PYTHON_VERSION'/' ./environment.yml
  - conda env create -n cw-geodata --file=environment.yml
  - source activate cw-geodata
  - python --version
  - pip install -q -e .[test]
  - pip install codecov pytest pytest-cov
# command to run tests
script:
  - pytest --cov=./

after_success:
  - codecov
